import Mobile1 from "../../Assets/Images/mobile-1.avif";
import Mobile2 from "../../Assets/Images/mobile-2.avif";
import Mobile3 from "../../Assets/Images/mobile-3.avif";
import Mobile4 from "../../Assets/Images/mobile-4.avif";
import Mobile5 from "../../Assets/Images/mobile-5.avif";
import Mobile6 from "../../Assets/Images/mobile-6.avif";
import Mobile7 from "../../Assets/Images/mobile-7.avif";
import Mobile8 from "../../Assets/Images/mobile-8.avif";
import Mobile9 from "../../Assets/Images/mobile-9.avif";
import Mobile10 from "../../Assets/Images/mobile-10.avif";
import Mobile11 from "../../Assets/Images/mobile-11.avif";
import Mobile12 from "../../Assets/Images/mobile-12.avif";
import Mobile13 from "../../Assets/Images/mobile-13.avif";
import Mobile14 from "../../Assets/Images/mobile-14.avif";
import Mobile15 from "../../Assets/Images/mobile-15.avif";
import Mobile16 from "../../Assets/Images/mobile-16.avif";
import Mobile17 from "../../Assets/Images/mobile-17.avif";
import Mobile18 from "../../Assets/Images/mobile-18.avif";
import Mobile19 from "../../Assets/Images/mobile-19.avif";





const products = [
  {
    id: 1,
    title: "Samsung Galaxy S26 Ultra Dual SIM Black 12GB RAM 256GB 5G - International...",
    image: Mobile1,
    rating: 4.6,
    reviews: 944,
    price: 3449,
    oldPrice: 4144,
    discount: 16,
    badge: null,
    delivery: "express",
    deliveryLabel: "Tomorrow",
    rank: "#32 in Smartphones",
  },
  {
    id: 2,
    title: "Apple iPhone 17 256GB Black 5G (Nano SIM + eSIM) With FaceTime - International...",
    image: Mobile2,
    rating: 4.6,
    reviews: 4700,
    price: 3299,
    oldPrice: null,
    discount: null,
    badge: null,
    delivery: "fast",
    deliveryLabel: "GET IN 45 MINS",
    stockNote: "Selling out fast",
  },
  {
    id: 3,
    title: "Apple iPhone 17 256GB (e-Sim only) Sage 5G With FaceTime - International...",
    image: Mobile3,
    rating: 4.6,
    reviews: 4700,
    price: 3149,
    oldPrice: 3399,
    discount: 7,
    badge: null,
    delivery: "express",
    deliveryLabel: "Tomorrow",
    stockNote: "Only 1 left in stock",
  },
  {
    id: 4,
    title: "OnePlus 15 Dual SIM Infinite Black with AI 16GB RAM 512GB 5G - International...",
    image: Mobile4,
    rating: 4.3,
    reviews: 415,
    price: 2849,
    oldPrice: 3089,
    discount: 7,
    badge: "noon exclusive",
    delivery: "express",
    deliveryLabel: "Tomorrow",
    stockNote: "Selling out fast",
  },
  {
    id: 5,
    title: "Apple iPhone 17 Pro 256 GB (e-Sim only) Cosmic Orange 5G With FaceTime -...",
    image: Mobile5,
    rating: 4.5,
    reviews: 26500,
    price: 4299,
    oldPrice: 4699,
    discount: 8,
    badge: null,
    delivery: "fast",
    deliveryLabel: "GET IN 45 MINS",
    stockNote: "Selling out fast",
  },
  {
    id: 6,
    title: "Apple iPhone 17 256GB Lavender 5G (Nano SIM + eSIM) With FaceTime -...",
    image: Mobile6,
    rating: 4.6,
    reviews: 4700,
    price: 3299,
    oldPrice: null,
    discount: null,
    badge: null,
    delivery: "fast",
    deliveryLabel: "GET IN 45 MINS",
    stockNote: "Selling out fast",
  },  {
    id: 6,
    title: "Apple iPhone 17 256GB Lavender 5G (Nano SIM + eSIM) With FaceTime -...",
    image: Mobile7,
    rating: 4.6,
    reviews: 4700,
    price: 3299,
    oldPrice: null,
    discount: null,
    badge: null,
    delivery: "fast",
    deliveryLabel: "GET IN 45 MINS",
    stockNote: "Selling out fast",
  },  {
    id: 6,
    title: "Apple iPhone 17 256GB Lavender 5G (Nano SIM + eSIM) With FaceTime -...",
    image: Mobile8,
    rating: 4.6,
    reviews: 4700,
    price: 3299,
    oldPrice: null,
    discount: null,
    badge: null,
    delivery: "fast",
    deliveryLabel: "GET IN 45 MINS",
    stockNote: "Selling out fast",
  },  {
    id: 6,
    title: "Apple iPhone 17 256GB Lavender 5G (Nano SIM + eSIM) With FaceTime -...",
    image: Mobile9,
    rating: 4.6,
    reviews: 4700,
    price: 3299,
    oldPrice: null,
    discount: null,
    badge: null,
    delivery: "fast",
    deliveryLabel: "GET IN 45 MINS",
    stockNote: "Selling out fast",
  },  {
    id: 6,
    title: "Apple iPhone 17 256GB Lavender 5G (Nano SIM + eSIM) With FaceTime -...",
    image: Mobile10,
    rating: 4.6,
    reviews: 4700,
    price: 3299,
    oldPrice: null,
    discount: null,
    badge: null,
    delivery: "fast",
    deliveryLabel: "GET IN 45 MINS",
    stockNote: "Selling out fast",
  },  {
    id: 6,
    title: "Apple iPhone 17 256GB Lavender 5G (Nano SIM + eSIM) With FaceTime -...",
    image: Mobile11,
    rating: 4.6,
    reviews: 4700,
    price: 3299,
    oldPrice: null,
    discount: null,
    badge: null,
    delivery: "fast",
    deliveryLabel: "GET IN 45 MINS",
    stockNote: "Selling out fast",
  },  {
    id: 6,
    title: "Apple iPhone 17 256GB Lavender 5G (Nano SIM + eSIM) With FaceTime -...",
    image: Mobile12,
    rating: 4.6,
    reviews: 4700,
    price: 3299,
    oldPrice: null,
    discount: null,
    badge: null,
    delivery: "fast",
    deliveryLabel: "GET IN 45 MINS",
    stockNote: "Selling out fast",
  }, {
    id: 6,
    title: "Apple iPhone 17 256GB Lavender 5G (Nano SIM + eSIM) With FaceTime -...",
    image: Mobile13,
    rating: 4.6,
    reviews: 4700,
    price: 3299,
    oldPrice: null,
    discount: null,
    badge: null,
    delivery: "fast",
    deliveryLabel: "GET IN 45 MINS",
    stockNote: "Selling out fast",
  }, {
    id: 6,
    title: "Apple iPhone 17 256GB Lavender 5G (Nano SIM + eSIM) With FaceTime -...",
    image: Mobile14,
    rating: 4.6,
    reviews: 4700,
    price: 3299,
    oldPrice: null,
    discount: null,
    badge: null,
    delivery: "fast",
    deliveryLabel: "GET IN 45 MINS",
    stockNote: "Selling out fast",
  }, {
    id: 6,
    title: "Apple iPhone 17 256GB Lavender 5G (Nano SIM + eSIM) With FaceTime -...",
    image: Mobile15,
    rating: 4.6,
    reviews: 4700,
    price: 3299,
    oldPrice: null,
    discount: null,
    badge: null,
    delivery: "fast",
    deliveryLabel: "GET IN 45 MINS",
    stockNote: "Selling out fast",
  }, {
    id: 6,
    title: "Apple iPhone 17 256GB Lavender 5G (Nano SIM + eSIM) With FaceTime -...",
    image: Mobile16,
    rating: 4.6,
    reviews: 4700,
    price: 3299,
    oldPrice: null,
    discount: null,
    badge: null,
    delivery: "fast",
    deliveryLabel: "GET IN 45 MINS",
    stockNote: "Selling out fast",
  }, {
    id: 6,
    title: "Apple iPhone 17 256GB Lavender 5G (Nano SIM + eSIM) With FaceTime -...",
    image: Mobile17,
    rating: 4.6,
    reviews: 4700,
    price: 3299,
    oldPrice: null,
    discount: null,
    badge: null,
    delivery: "fast",
    deliveryLabel: "GET IN 45 MINS",
    stockNote: "Selling out fast",
  }, {
    id: 6,
    title: "Apple iPhone 17 256GB Lavender 5G (Nano SIM + eSIM) With FaceTime -...",
    image: Mobile18,
    rating: 4.6,
    reviews: 4700,
    price: 3299,
    oldPrice: null,
    discount: null,
    badge: null,
    delivery: "fast",
    deliveryLabel: "GET IN 45 MINS",
    stockNote: "Selling out fast",
  },
];

export default products;